version: '3'
services:

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./db/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: magic
