spring:
  datasource:
    url: jdbc:mysql://localhost:3307/magic?characterEncoding=UTF-8
    username: root
    password: magic
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.magi.demo.Model
  mapperLocations: classpath:mapping/*.xml